---
title: "Speedrunning in Videogames"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(drc)
library(nlme)
#library(aomisc)
require(dplyr)
require(ggplot2)
require(ggExtra)
require(cowplot)
require(igraph)

correct_delta_value <- function(data_to_use){
  
  # fix values
  data_to_use$delta_normalised_run_time <-c(data_to_use$delta_normalised_run_time[2:(length(data_to_use$delta_normalised_run_time))], 0)
  
  # return
  return(data_to_use)
}

calculate_record_duration <- function(data_to_use){
  
  # calculate record duration
  data_to_use$record_duration <- c(0, data_to_use$normalised_run_date[1:(length(data_to_use$normalised_run_date) - 1)] - data_to_use$normalised_run_date[2:length(data_to_use$normalised_run_date)])
  
  # return
  return(data_to_use)
  
}

obtain_time_window_with_max_delta <- function(data_to_use){
  
  # try when highest delta was set
  data_to_use$max_delta_num_tries <- which.max(data_to_use$delta_normalised_run_time)[1]
  # value of largest delta
  data_to_use$largest_delta <- max(data_to_use$delta_normalised_run_time)
  # time when largest delta was set
  data_to_use$run_date_largest_delta <- data_to_use$normalised_run_date[which.max(data_to_use$delta_normalised_run_time)[1]]
  
  # return data
  return(data_to_use) 
}

```

```{r, echo = FALSE, message=FALSE, warning=FALSE}
# data wrangling
data <- read.csv('clean_world_record_data.csv', row.names = 1)

data_record_duration <- data %>% 
  group_by(record_compound_id) %>%
  group_modify(~calculate_record_duration(.))

data_record_duration <- data_record_duration %>%
  filter(record_duration > 0)

data_delta <-  data %>% 
  group_by(record_compound_id) %>%
  group_modify(~correct_delta_value(.))

data_delta <- data_delta %>%
  filter(delta_normalised_run_time > 0)

data_clean_largest_delta <- data_delta %>% 
  group_by(record_compound_id) %>%
  group_modify(~obtain_time_window_with_max_delta(.)) 

data_max_delta_time_window <- data_clean_largest_delta %>% 
  distinct(record_compound_id, .keep_all= TRUE)

## NETORK ANALYSIS

convert_raw_data_to_network <- function(data_to_process){
  
  # Extract names of player and record
  gamer_id <- unique(data_to_process[,2])
  record_id <- unique(data_to_process[,1])
  
  # create matrix of zeros
  incidence_mat <- matrix(0, nrow = length(gamer_id), ncol = length(record_id))
  rownames(incidence_mat) <- gamer_id
  colnames(incidence_mat) <- record_id
  
  # fill incidence matrix
  for (i in 1:nrow(data_to_process)) {
    
    incidence_mat[data_to_process[i,2],data_to_process[i,1]] <-  incidence_mat[data_to_process[i,2],data_to_process[i,1]] + 1
    
  }
  
  return(incidence_mat)
  
}

# Build bipartite network from raw data
network_record_level <- data %>% 
  select(record_compound_id, run_player_id) %>%
  convert_raw_data_to_network(.) %>%
  graph_from_incidence_matrix(., weighted = TRUE)

# Calculate node descriptors
degree_values <- degree(network_record_level)
names_gamer_and_game <- names(degree_values)
type_node <- as.numeric(V(network_record_level)$type)
betweenness_centrality_values <- betweenness(network_record_level)
V(network_record_level)$color <- ifelse(V(network_record_level)$type == 1, "lightblue", "orange")

network_clean_data <- as.data.frame(cbind(names_gamer_and_game, type_node, unname(degree_values), unname(betweenness_centrality_values)))
colnames(network_clean_data) <- c('name_id', 'node_type', 'degree', 'betweenness_centrality')

player_network_clean_data <- network_clean_data %>% filter(node_type == 0)
game_network_clean_data <- network_clean_data %>% filter(node_type == 1)

player_network_clean_data_with_delta <- data_delta %>% left_join(player_network_clean_data, by = c("run_player_id" = "name_id"))
summarised_player_network_clean_data_with_delta <- player_network_clean_data_with_delta %>% group_by(degree) %>% 
  summarise(mean_delta_normalised_run_time = mean(delta_normalised_run_time), 
            se_mean_delta_normalised_run_time = sd(delta_normalised_run_time)/sqrt(length(delta_normalised_run_time)),
            mean_normalised_run_date = mean(normalised_run_date),
            se_mean_normalised_run_date = sd(normalised_run_date)/sqrt(length(normalised_run_date))) 

player_network_clean_data_with_max_delta <- data_max_delta_time_window %>% left_join(player_network_clean_data, by = c("run_player_id" = "name_id"))

player_network_clean_data_with_duration <- data_record_duration %>% left_join(player_network_clean_data, by = c("run_player_id" = "name_id"))
summarised_player_network_clean_data_with_duration <- player_network_clean_data_with_duration %>% group_by(degree) %>% 
  summarise(mean_record_duration = mean(record_duration), 
            se = sd(record_duration)/sqrt(length(record_duration))) 

aa <- player_network_clean_data_with_delta %>% group_by(degree) %>%
  summarise(count_delta = n())

bb <- player_network_clean_data_with_max_delta %>% group_by(degree) %>%
  summarise(count_max_delta = n()) 

cc <- aa %>% left_join(bb) %>% mutate(prob = count_max_delta/count_delta)
cc[is.na(cc)] <- 0

xx <- player_network_clean_data_with_duration %>% 
  group_by(degree) %>% 
  summarise(count_duration = n())

zz <- player_network_clean_data_with_duration %>% 
  group_by(record_compound_id) %>% 
  filter(record_duration == max(record_duration))

yy <- zz %>% 
  group_by(degree) %>% 
  summarise(count_max_duration = n())

cc2 <- xx %>% left_join(yy) %>% mutate(prob = count_max_duration/count_duration)
cc2[is.na(cc2)] <- 0


game_network_clean_data_with_delta <- data_delta %>% 
  left_join(game_network_clean_data, by = c("record_compound_id" = "name_id"))

summarised_game_network_clean_data_with_delta <- game_network_clean_data_with_delta %>% group_by(degree) %>% 
  summarise(mean_delta_normalised_run_time = mean(delta_normalised_run_time), 
            se_mean_delta_normalised_run_time = sd(delta_normalised_run_time)/sqrt(length(delta_normalised_run_time)),
            mean_normalised_run_date = mean(normalised_run_date),
            se_mean_normalised_run_date = sd(normalised_run_date)/sqrt(length(normalised_run_date))) 
game_network_clean_data_with_max_delta <- data_max_delta_time_window %>% left_join(game_network_clean_data, by = c("record_compound_id" = "name_id"))

summarised_game_network_duration_largest_impact <- game_network_clean_data_with_max_delta %>% 
  group_by(degree) %>% 
  summarise(mean_time = mean(run_date_largest_delta),
            se_mean_time = sd(run_date_largest_delta)/sqrt(length(run_date_largest_delta)))

game_network_clean_data_with_duration <- data_record_duration %>% left_join(game_network_clean_data, by = c("record_compound_id" = "name_id"))
summarised_game_network_clean_data_with_duration <- game_network_clean_data_with_duration %>% group_by(degree) %>% 
  summarise(mean_record_duration = mean(record_duration), 
            se = sd(record_duration)/sqrt(length(record_duration))) 

summarised_game_network_duration_time <- game_network_clean_data_with_duration %>% 
  group_by(record_compound_id) %>% 
  filter(record_duration == max(record_duration)) %>% 
  group_by(degree) %>% 
  summarise(mean_time = mean(normalised_run_date),
            se_mean_time = sd(normalised_run_date)/sqrt(length(normalised_run_date)))

game_aa <- game_network_clean_data_with_delta %>% group_by(degree) %>%
  summarise(count_delta = n())

game_bb <- game_network_clean_data_with_max_delta %>% group_by(degree) %>%
  summarise(count_max_delta = n()) 

game_cc <- game_aa %>% left_join(game_bb) %>% mutate(prob = count_max_delta/count_delta)
game_cc[is.na(game_cc)] <- 0

game_xx <- game_network_clean_data_with_duration %>% 
  group_by(degree) %>% 
  summarise(count_duration = n())

game_zz <- game_network_clean_data_with_duration %>% 
  group_by(record_compound_id) %>% 
  filter(record_duration == max(record_duration))

game_yy <- game_zz %>% 
  group_by(degree) %>% 
  summarise(count_max_duration = n())

game_cc2 <- game_xx %>% left_join(game_yy) %>% mutate(prob = count_max_duration/count_duration)
game_cc2[is.na(game_cc2)] <- 0
```

### Figure 1

```{r, echo = FALSE, warning=FALSE, message=FALSE, fig.align='center', fig.cap='\nEvolution of world records. A) The progression of all speedrunning records. The world record time is standardised (y-axis), such that 1 represents the speedrunning time of the first record and 0 represents the speedrunning time of the current record. The date when the record was set is standardised (x-axis), such that 0 represents the date at which the first record was set and 1 represents the date at which the current world record was set. B) The impact of new records diminishes as time passes. Delta WR Time is calculated as the difference in time of a given record and the time of the previous record. C) The impact of a record does not predict its duration. WR duration is calculated as the difference in run date between a given record and the ensuing record. D) The time reduced by the most impactful records decreases as time passes. For each game, the most impactful record is identified and its Delta WR Time is plotted against the time at which it was set.'}

# Figure 1

figure_A <- ggplot(data, aes(x = normalised_run_date, y = normalised_run_time)) + 
  geom_line(aes(group = record_compound_id), size = 0.01) +
  theme_minimal() + xlab('Run date') + 
  ylab('WR Time') + theme(aspect.ratio = 1)


figure_B <- ggplot(data_delta, aes(x = normalised_run_date, y = delta_normalised_run_time)) + 
  geom_point(size = 0.01) +
  theme_minimal() + xlab('Run date') + 
  ylab('Delta WR Time') + theme(aspect.ratio = 1) + geom_smooth(method = 'lm')

figure_B <- ggMarginal(figure_B, type="histogram", size=10, alpha = 0.7)

# summary(lm(delta_normalised_run_time~normalised_run_date, data = data_delta))

figure_D <- ggplot(data = data_max_delta_time_window, aes(x = run_date_largest_delta, y = largest_delta)) +
  geom_point(size = 0.01) +
  theme_minimal() + xlab('Run date') + 
  ylab('Largest Delta WR Time') + theme(aspect.ratio = 1) + geom_smooth(method = 'lm')

figure_D <- ggMarginal(figure_D, type="histogram", size=10, alpha = 0.7)

#summary(lm(largest_delta~run_date_largest_delta, data = data_max_delta_time_window))

figure_4 <- ggplot(data_record_duration, aes(x = normalised_run_date, y = record_duration)) + 
    geom_point(size = 0.01) +
    theme_minimal() + xlab('Run date') + 
    ylab('WR duration') + theme(aspect.ratio = 1) + geom_smooth(method = 'lm')

figure_4 <- ggMarginal(figure_4, type="histogram", size=10, alpha = 0.7)

figure_C <- ggplot(data_record_duration, aes(x = delta_normalised_run_time, y = record_duration)) + 
  geom_point(size = 0.01) +
  theme_minimal() + xlab('Delta WR Time') + 
  ylab('WR duration') + theme(aspect.ratio = 1) + geom_smooth(method = 'lm')

 # summary(lm(record_duration~delta_normalised_run_time, data = data_record_duration))

figure_C <- ggMarginal(figure_C, type="histogram", size=10, alpha = 0.7)

figure_1 <- plot_grid(figure_A, figure_B, figure_C, figure_D, labels = 'AUTO')

figure_1
```

### Figure 2

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.align='center', fig.cap='The speedrunning network. A) Degree distribution of players. Players with high degree are those which set records in multiple games. B) Degree distribution of games. Games with high degree are those where many players set a record. Note that data was wrangled such that only games with at least five set records were included in the dataset.'}

#figure_one <- plot(network_record_level, edge.width=E(network_record_level)$weight*0.3,
#     vertex.size= degree(network_record_level)*0.3, vertex.label = NA, edge.color = 'black')

figure_E <- ggplot(data = player_network_clean_data, aes(x =  as.numeric(degree))) + geom_histogram(color = 'black', alpha = 0.6) + theme_minimal() +
  xlab('Degree') + ylab('Frequency') +  ggtitle('Player Degree Distribution') + theme(aspect.ratio = 1)

figure_F <- ggplot(data = game_network_clean_data, aes(x =  as.numeric(degree))) + geom_histogram(color = 'black', alpha = 0.6) + theme_minimal() + 
  xlab('Degree') + ylab('Frequency') + ggtitle('Game Degree Distribution')  + theme(aspect.ratio = 1)

figure_2 <- plot_grid(figure_E, figure_F, labels = 'AUTO')

figure_2
```

### Figure 3

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.align = 'center', fig.cap = 'The effect of player degree on record impact and duration. The degree of a player does not affect the probability of setting the most impactful (A) or longest lasting (B) records, nor the average impact (C) or duration (D) of a record.'}

figure_H <- ggplot(data = cc, aes(x = as.numeric(degree), y = prob)) + 
  geom_point(size = 0.7) + theme_minimal() + xlab('Player degree') + ylab('Fraction of times\n WR was most impactful') + theme(aspect.ratio = 1) +
  geom_smooth(method = 'lm')

#summary(lm(prob~as.numeric(degree), data = cc))

figure_H2 <- ggplot(data = cc2, aes(x = as.numeric(degree), y = prob)) + 
  geom_point(size = 0.7) + theme_minimal() + xlab('Player degree') + ylab('Fraction of times\n WR was longest lasting') + theme(aspect.ratio = 1) +
  geom_smooth(method = 'lm')

#summary(lm(prob~as.numeric(degree), data = cc2))

figure_F2 <- ggplot(data = summarised_player_network_clean_data_with_delta,
       aes(x = as.numeric(degree), y = mean_delta_normalised_run_time)) + 
  geom_pointrange(data = summarised_player_network_clean_data_with_delta,
                  aes(x = as.numeric(degree), y = mean_delta_normalised_run_time,
                  ymin = mean_delta_normalised_run_time - se_mean_delta_normalised_run_time, 
                  ymax = mean_delta_normalised_run_time + se_mean_delta_normalised_run_time), size = 0.1, width = 0.2) + geom_smooth(method = 'lm') + 
  theme_minimal() + theme(aspect.ratio = 1) + xlab('Player degree') + ylab('Mean Delta WR Time')

#summary(lm(mean_delta_normalised_run_time~as.numeric(degree), data = summarised_player_network_clean_data_with_delta))

figure_I2 <- ggplot(data = summarised_player_network_clean_data_with_duration,
                    aes(x = as.numeric(degree), y = mean_record_duration)) + 
  geom_pointrange(data = summarised_player_network_clean_data_with_duration,
                  aes(x = as.numeric(degree), y = mean_record_duration,
                      ymin = mean_record_duration - se, 
                      ymax = mean_record_duration + se), size = 0.1, width = 0.2) + geom_smooth(method = 'lm') + 
  theme_minimal() + theme(aspect.ratio = 1) + xlab('Player degree') + ylab('Mean record duration')

#summary(lm(mean_record_duration~as.numeric(degree), data = summarised_player_network_clean_data_with_duration))

figure_3V2 <- plot_grid(figure_H, figure_H2, figure_F2, figure_I2, labels = 'AUTO', nrow = 2)

figure_3V2
```

### Figure 4

```{r, echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center', fig.cap = 'The effect of game degree on record impact and duration. A) Games with higher degree tend to have impactful records set early on. B) Games with low degree tend to have long lasting records set early on (note, this is marginal). Games with high degree have on average records of low impact (C) and low duration (D).'}

figure_mean_impact <- ggplot(data = summarised_game_network_duration_largest_impact,
       aes(x = as.numeric(degree), y = mean_time)) + 
  geom_pointrange(data = summarised_game_network_duration_largest_impact,
                  aes(x = as.numeric(degree), y = mean_time,
                  ymin = mean_time - se_mean_time, 
                  ymax = mean_time + se_mean_time), size = 0.1, width = 0.2)  + 
  theme_minimal() + theme(aspect.ratio = 1) + xlab('Game degree') + ylab('Mean Run Date\n when most impactful record\n was set') + geom_smooth(method = 'lm')

#summary(lm(mean_time~as.numeric(degree), data = summarised_game_network_duration_largest_impact))

figure_mean_duration <- ggplot(data = summarised_game_network_duration_time,
       aes(x = as.numeric(degree), y = mean_time)) + 
  geom_pointrange(data = summarised_game_network_duration_time,
                  aes(x = as.numeric(degree), y = mean_time,
                  ymin = mean_time - se_mean_time, 
                  ymax = mean_time + se_mean_time), size = 0.1, width = 0.2)  + 
  theme_minimal() + theme(aspect.ratio = 1) + xlab('Game degree') + ylab('Mean Run Date\n when longest lasting record\n was set') + geom_smooth(method = 'lm')

#summary(lm(mean_time~as.numeric(degree), data = summarised_game_network_duration_time))

figure_game_F2 <- ggplot(data = summarised_game_network_clean_data_with_delta,
       aes(x = as.numeric(degree), y = mean_delta_normalised_run_time)) + 
  geom_pointrange(data = summarised_game_network_clean_data_with_delta,
                  aes(x = as.numeric(degree), y = mean_delta_normalised_run_time,
                  ymin = mean_delta_normalised_run_time - se_mean_delta_normalised_run_time, 
                  ymax = mean_delta_normalised_run_time + se_mean_delta_normalised_run_time), size = 0.1, width = 0.2)  + 
  theme_minimal() + theme(aspect.ratio = 1) + xlab('Game degree') + ylab('Mean Delta WR Time')

#summary(lm(mean_delta_normalised_run_time~as.numeric(degree), data = summarised_player_network_clean_data_with_delta))

figure_game_I2 <- ggplot(data = summarised_game_network_clean_data_with_duration,
                    aes(x = as.numeric(degree), y = mean_record_duration)) + 
  geom_pointrange(data = summarised_game_network_clean_data_with_duration,
                  aes(x = as.numeric(degree), y = mean_record_duration,
                      ymin = mean_record_duration - se, 
                      ymax = mean_record_duration + se), size = 0.1, width = 0.2) + 
  theme_minimal() + theme(aspect.ratio = 1) + xlab('Game degree') + ylab('Mean record duration')

#summary(lm(mean_record_duration~as.numeric(degree), data = summarised_player_network_clean_data_with_duration))

figure_game_3V2 <- plot_grid(figure_mean_impact, figure_mean_duration, figure_game_F2, figure_game_I2, labels = 'AUTO', nrow = 2)

figure_game_3V2

```

